import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Characters from "./characters";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        {/* Favicon pour tous les navigateurs */}
        <link rel="icon" href="/favicon.ico" />
        
        {/* Favicons pour différents appareils */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        
        {/* Manifest Web App pour les applications PWA */}
        <link rel="manifest" href="/site.webmanifest" />
        
        {/* Meta tags pour l'Apple Touch */}
        <meta name="apple-mobile-web-app-title" content="Next App" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

        {/* Icone pour les écrans haute résolution */}
        <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png" />
        
        {/* Apple iOS icon */}
        <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <div>
        <Characters />
      </div>
    </>
  );
}
